<a href="https://colab.research.google.com/github/adapateja/FML-lab/blob/main/13_)IMP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**In these simplified implementations, the activation functions are applied to individual scalar inputs, and the outputs are calculated based on the respective formulas. Keep in mind that these implementations are not optimized for handling large datasets efficiently, as they are intended to provide a basic understanding of the activation functions.**




In [1]:
#a. Sigmoid Activation Function:

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Example usage
x = np.array([-1, 0, 1])
print(sigmoid(x))


[0.26894142 0.5        0.73105858]


In [3]:
#b. Tanh Activation Function:

import numpy as np

def tanh(x):
    return np.tanh(x)

# Example usage
x = np.array([-1, 0, 1])
print(tanh(x))


[-0.76159416  0.          0.76159416]


In [2]:
#c. ReLU (Rectified Linear Unit) Activation Function:

import numpy as np

def relu(x):
    return np.maximum(0, x)

# Example usage
x = np.array([-1, 0, 1])
print(relu(x))


[0 0 1]


In [4]:
#d. Softmax Activation Function (for multi-class classification):

import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / np.sum(e_x, axis=1, keepdims=True)

# Example usage
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(softmax(x))


[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]
